name: Dev Branch Validation

on:
  push:
    branches: [dev]

jobs:
  validate-dev:
    name: Validate Dev Branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Test CLI functionality
        run: |
          npm link
          mkdir -p /tmp/dev-test
          cd /tmp/dev-test
          create-revitt-app dev-test-app --template default
          cd dev-test-app
          npm install
          npm run build
          npm run type-check
          echo "✅ Dev branch: CLI creates working apps"
          
      - name: Clean up
        if: always()
        run: |
          npm unlink -g create-revitt-app || true
          rm -rf /tmp/dev-test